### ISSUE TITLE
Check out all files in a folder

### ISSUE THREAD

**Issue by 1rosehip** [natelong/p4#6]
Hello,
As much as I can see for now it's only possible to check out a single file.
It could be nice to have possibility to check out all items in the given **folder** with and without wilcard:

`p4.edit('path-to-folder', function(err, stdout) {
    console.log(stdout);
});`

`p4.edit('path-to-folder/*.js', function(err, stdout) {
    console.log(stdout);
});`

Thanks for the helpful lib

**Comment by tivac** [comment]
You can use the [p4 wildcard](https://www.perforce.com/perforce/doc.current/manuals/cmdref/Content/CmdRef/filespecs.html) syntax to open multiple files for edit.

**Comment by 1rosehip** [comment]
It works, thank you!
